import { Header } from "./Header/Header";
import { Images } from "./Images/Images";
import { Information } from "./Information/Information";
import { Price } from "./Price/Price";
import {Amenities} from "./Amenities/Amenities";
import { CheckInDate } from "./Check-inDate/Check-inDate";
import { Reviews } from "./Reviews/Reviews";
import { Location } from "./Location/Location";
import { HostedBy } from "./HostedBy/HostedBy";
import { Slider } from "./Slider/Slider";
import { HouseCarousel } from "./HouseCarousel/HouseCarousel";
export {Header,Images, Information, Price, Amenities, CheckInDate, Reviews, Location, HostedBy, Slider, HouseCarousel};